(let ((x 0))
	(defun inc()
		(incf x))
	(defun dec()
		(decf x)))

(let ((x 0))
	(defvar inc (lambda()
		(incf x)))
	(defvar dec (lambda()
		(decf x))))

(let ((x 0))
	(defvar cnt (lambda(op)
		(cond ((eq op 'inc)
				(incf x))
			((eq op 'dec)
				(decf x))
			(t nil)))))